### ISSUE TITLE
cannot sign in with amazon.nl account

### ISSUE THREAD

**Issue by RobVerduijn** [Sandmann79/xbmc#540]
**Addon used**
- [X] Amazon VOD (plugin.video.amazon-test)
- [ ] Browser Launcher (plugin.program.browser.launcher)

- Addon version: 

**Account type**
- [x] primevideo.com
- [ ] amazon.(com/co.uk/de/jp)

**System Setup (please provide the following information):**
- Hardware:
- OS version: fedora33 x86_64
- Kodi version number: matrix 19.0-BETA2 (18.9.821)

**Upload Logs**

**Describe the bug**

I saw in the code that my country was not present in the options. (amazon.nl has been created in 2020)
it also says :
Error Contents: Invalid URL '/gp/aw/si.html': No schema supplied. Perhaps you meant http:///gp/aw/si.html
Which is probable the reason why.

if you require more detailed logs please let me know

**Comment by Varstahl** [comment]
Most countries use PrimeVideo.com, except those 4 which had the service before the rest of the world. You most likely are incurring in a login issue which has been fixed but not published yet.

Replace network.py [with this version](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/resources/lib/network.py), then you should be able to login.

**Comment by RobVerduijn** [comment]
I replaced the file but it keeps coming back with the same error:

```
Error Type: <class 'requests.exceptions.MissingSchema'>
Error Contents: Invalid URL '/gp/aw/si.html': No schema supplied. Perhaps you meant http:///gp/aw/si.html?
Traceback (most recent call last):
  File "/home/kodi/.kodi/addons/plugin.video.amazon-test/default.py", line 5, in <module> EntryPoint()
  File "/home/kodi/.kodi/addons/plugin.video.amazon-test/resources/lib/startup.py", line 102, in EntryPoint exec('{}()'.format(mode))
  File "<string>", line 1, in <module>
  File "/home/kodi/.kodi/addons/plugin.video.amazon-test/resources/lib/network.py", line 581, in LogIn br.open(user['baseurl'] + ('/gp/aw/si.html' if not user['pv'] else '/auth-redirect/'))
  File "/home/kodi/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/stateful_browser.py", line 133, in open resp = self.get(url, *args, **kwargs)
  File "/home/kodi/.kodi/addons/script.module.mechanicalsoup/lib/mechanicalsoup/browser.py", line 124, in get response = self.session.get(*args, **kwargs)
  File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 546, in get return self.request('GET', url, **kwargs)
  File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 519, in request prep = self.prepare_request(req)
  File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 452, in prepare_request p.prepare(
  File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 313, in prepare self.prepare_url(url, params)
  File "/home/kodi/.kodi/addons/script.module.requests/lib/requests/models.py", line 387, in prepare_url raise MissingSchema(error)
  requests.exceptions.MissingSchema: Invalid URL '/gp/aw/si.html': No schema supplied. Perhaps you meant http:///gp/aw/si.html?
```

**Comment by Varstahl** [comment]
That doesn't make any sense. Try to disconnect and then sign in back again with the addon.

**Comment by RobVerduijn** [comment]
this is a clean installation in a vm.
There was no old login to disconnect.

Rob

**Comment by RobVerduijn** [comment]
I cleaned all previous settings to ensure there was no crud left.
still fails with the same error.

**Comment by RobVerduijn** [comment]
I see another error (who I missed that one before, i don't know)

something is wrong with the ssl connection

```
ERROR <general>: [Amazon VOD] Error reason: HTTPSConnectionPool(host='na.api.amazonvideo.com', port=443): Max retries exceeded with url: /cdp/usage/v2/GetAppStartupConfig?deviceTypeID=A28RQHJKHM2A2W&deviceID=5b7257436007eda862ac5f9e459ff6546b9836889c6f3b441b39ebcc&firmware=1&version=1&format=json (Caused by SSLError(SSLError(1, '[SSL: UNSUPPORTED_PROTOCOL] unsupported protocol (_ssl.c:1123)'))) (SSLError)
```

**Comment by Varstahl** [comment]
Hmm, that's probably because `na.api.amazonvideo.com` TLSv1 connections, and since it's dated and mostly unsupported due to insecurity, most distros block them outright, such as Ubuntu and, apparently, Fedora.

It's a platform specific SSL issue, can't help you much with that.

**Comment by RobVerduijn** [comment]
hi,

sorry to keep bothering

ssl 1.0 was indeed the one causing that
on fedora you need to install the compat-openssl10 package to deal with that

it makes the ssl error disappear

however now when I am trying to login and the plugin seem to wait forever on the 'animated waiting gif' screen
```
2021-02-05 11:14:10.949 T:1245     INFO <general>: initializing python engine.
2021-02-05 11:14:10.951 T:1245     INFO <general>: CPythonInvoker(4, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): script successfully run
2021-02-05 11:14:10.964 T:1049  WARNING <general>: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
```

**Comment by Varstahl** [comment]
From the addon connection settings try to disconnect the account and then sign in again. Unless it already connected, in which case sometimes restarting Kodi works too.

**Comment by RobVerduijn** [comment]
hi
I tried:
login ... endless wait for screen to continue
<esc>
plugin->config->connections->remove crededentals and cookies
I get an error... no credentials present

I reboot
I try to configure login again.... same wait screen not proceeding

when in debug mode in the logs there are no errors, just this warning a couple times :
```
WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
```
also it is mentioning the following
```
2021-02-05 13:24:31.999 T:1103    DEBUG <general>: GetLanguageInvoker - Reusing LanguageInvokerThread 9 for script /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py
2021-02-05 13:24:31.999 T:1324     INFO <general>: initializing python engine.
2021-02-05 13:24:31.999 T:1324    DEBUG <general>: CPythonInvoker(9, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): start processing
2021-02-05 13:24:31.999 T:1324    DEBUG <general>: CPythonInvoker(9, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): entering source directory /home/kodi/.kodi/addons/plugin.video.amazon-test
2021-02-05 13:24:31.999 T:1324    DEBUG <general>: CPythonInvoker(9, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): instantiating addon using automatically obtained id of "plugin.video.amazon-test" dependent on version 3.0.0 of the xbmc.python api
2021-02-05 13:24:32.000 T:1324    DEBUG <general>: [Amazon VOD] Requested {'mode': 'LogIn'}
2021-02-05 13:24:32.001 T:1324    DEBUG <CAddonSettings[plugin.video.amazon-test]>: trying to load setting definitions from old format...
2021-02-05 13:24:32.001 T:1324     INFO <general>: CPythonInvoker(9, /home/kodi/.kodi/addons/plugin.video.amazon-test/default.py): script successfully run
2021-02-05 13:24:32.236 T:1103    DEBUG <general>: ------ Window Deinit (DialogAddonSettings.xml) ------
```
but no real errors anywhere

**Comment by BuggStream** [comment]
I ran into the same issue on Fedora 35, but managed to circumvent it by using the flatpak version of kodi.

**Comment by RobVerduijn** [comment]
I also switched to kinoite with the kodi flatpak version.


However what might work for you is setting the crypto policies to legacy, then the insecure ssl is allowed again
you might also need to install the openssl1.1 rpm
```
update-crypto-policies --set LEGACY
```
see [fedora statement](https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2)
